(() => {
  const won=n=>Math.round(Number(n||0)).toLocaleString('ko-KR')+'원', num=(n,d=4)=>Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:d});
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stamp=v=>String(v||'').slice(5,16).replace('T',' '), cls=n=>Number(n)>=0?'up':'down';
  async function load(){
    const bust='?v='+Date.now();
    const [state,latest,status]=await Promise.all([
      fetch('monitor_data/paper_week.json'+bust,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('투자 기록을 불러오지 못했습니다');return r.json()}),
      fetch('monitor_data/latest.json'+bust,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('코인 지표를 불러오지 못했습니다');return r.json()}),
      fetch('automation/status_10m.json'+bust,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('자동화 상태를 불러오지 못했습니다');return r.json()})]);
    const metrics=Object.fromEntries((latest.items||[]).map(x=>[x.symbol,x])),positions=Object.entries(state.positions||{});
    const value=Number(status.coin?.value||state.cash||0),ret=Number(status.coin?.returnPct||0),sold=(state.trades||[]).filter(x=>x.side==='SELL'),wins=sold.filter(x=>Number(x.pnl)>0).length;
    const closedReturns=sold.map(x=>Number(x.returnPct)).filter(Number.isFinite),winningReturns=closedReturns.filter(x=>x>0),losingReturns=closedReturns.filter(x=>x<=0);
    const winRate=closedReturns.length?winningReturns.length/closedReturns.length:0,avgWin=winningReturns.length?winningReturns.reduce((a,b)=>a+b,0)/winningReturns.length:0,avgLoss=losingReturns.length?Math.abs(losingReturns.reduce((a,b)=>a+b,0)/losingReturns.length):0;
    const expectancy=closedReturns.length?winRate*avgWin-(1-winRate)*avgLoss:null;
    const checkedAt=status.coinUpdatedAt||status.time,age=Date.now()-Date.parse(checkedAt||0),healthy=Number.isFinite(age)&&age<=30*60*1000;
    const posRows=positions.map(([symbol,p])=>{const x=metrics[symbol]||{},entry=Number(p.entry),target=entry*1.06,current=Number(x.price||entry),gain=(current/entry-1)*100;return `<tr><td><b>${esc(symbol)}</b> ${esc(p.name)}</td><td>${num(entry)}</td><td><b>${num(target)}</b> <span class="target-rate">(+6%)</span></td><td>${num(current)}</td><td class="${cls(gain)}">${gain>=0?'+':''}${gain.toFixed(2)}%</td><td>${esc(x.comboScore??p.score??'—')}/7</td><td>${num(p.atrPct,2)}%</td></tr>`}).join('')||'<tr><td colspan="7">현재 매수 조건을 충족한 종목이 없어 현금 대기 중입니다.</td></tr>';
    const tradeEntries=new Map(),normalizedTrades=(state.trades||[]).map(t=>{let entryPrice=t.entryPrice??t.entry??null;if(t.side==='BUY'){entryPrice=Number(t.price);tradeEntries.set(t.symbol,entryPrice)}else if(t.side==='SELL'){entryPrice=entryPrice??tradeEntries.get(t.symbol)??null;tradeEntries.delete(t.symbol)}return {...t,entryPrice}});
    const tradeRows=[...normalizedTrades].reverse().map(t=>{const sold=t.side==='SELL',rate=sold&&t.returnPct!=null?Number(t.returnPct):null;return `<tr><td>${stamp(t.time)}</td><td class="${t.side==='BUY'?'up':'down'}">${esc(t.side)}</td><td><b>${esc(t.symbol)}</b> ${esc(t.name)}</td><td>${num(t.entryPrice??t.price)}</td><td>${sold?num(t.price):'—'}</td><td class="${rate==null?'':cls(rate)}">${rate==null?'보유 중':`${rate>=0?'+':''}${rate.toFixed(2)}%`}</td><td class="${t.pnl==null?'':cls(t.pnl)}">${t.pnl==null?'—':`${Number(t.pnl)>=0?'+':''}${won(t.pnl)}`}</td><td>${won(t.fee)}</td><td>${esc(t.reason)}</td></tr>`}).join('')||'<tr><td colspan="9">아직 체결이 없습니다.</td></tr>';
    const journals=[...(state.journal||[])].reverse().map(j=>`<article class="journal"><div class="journal-time"><b>${stamp(j.time)}</b><span>${esc(j.market||j.session)}</span></div><div class="journal-notes">${(j.notes||[]).map(n=>typeof n==='string'?`<div class="thought watch"><span class="decision">WATCH</span><p>${esc(n)}</p></div>`:`<div class="thought ${esc(String(n.type||'watch').toLowerCase())}"><span class="decision">${esc(n.type)}</span><b>${esc(n.symbol)} ${esc(n.name)}</b><p>${esc(n.comment)}</p></div>`).join('')}</div></article>`).join('');
    const main=document.querySelector('main.wrap');if(!main)throw Error('화면 본문을 찾지 못했습니다');
    main.innerHTML=`<div class="sub">PAPER TRADING · ${esc(state.start)} ~ ${esc(state.end)}</div><h1>추천 조합 1주일 가상투자</h1><p class="sub">실제 주문은 전혀 발생하지 않습니다. 최신 완성 1시간봉 신호를 사용하고 10분마다 현재가로 가상 체결 여부를 판단합니다.</p><p class="live-status ${healthy?'ok':'warn'}"><b>● ${healthy?'GitHub 자동화 정상':'자동화 갱신 지연 · Actions 확인 필요'}</b> · 마지막 코인 점검 ${esc(checkedAt)} · 사용 신호 ${esc(status.signalTime||latest.time)} · 실제 주문 ${Number(status.actualOrders||0)}건</p><div class="cards performance-cards"><div class="card"><span>가상자산</span><b>${won(value)}</b></div><div class="card"><span>누적수익률</span><b class="${cls(ret)}">${ret>=0?'+':''}${ret.toFixed(2)}%</b></div><div class="card"><span>현금</span><b>${won(state.cash)}</b></div><div class="card"><span>보유종목</span><b>${positions.length}/5</b></div><div class="card"><span>승률</span><b>${sold.length?(wins/sold.length*100).toFixed(1):'0.0'}%</b><small>청산 ${sold.length}건</small></div><div class="card expectancy-card"><span>거래당 기대수익 ⓘ</span><b class="${expectancy==null?'':cls(expectancy)}">${expectancy==null?'표본 대기':`${expectancy>=0?'+':''}${expectancy.toFixed(2)}%`}</b><small>승률×평균이익 − 패률×평균손실</small></div></div><section class="panel expectancy-help"><h2>기대수익을 이렇게 읽으세요</h2><p><b>${expectancy==null?'아직 청산 거래가 없어 계산할 수 없습니다.':`현재 완료 거래 1건당 평균 기대값은 ${expectancy>=0?'+':''}${expectancy.toFixed(2)}%입니다.`}</b></p><p class="sub">수수료와 슬리피지가 반영된 매도 수익률로 계산합니다. 표본이 30건 미만이면 참고값, 100건 이상부터 전략 비교값으로 사용하세요.</p></section><section class="panel"><h2>자산 변화</h2><canvas id="chart" width="1200" height="210"></canvas></section><section class="panel"><h2>현재 가상 보유</h2><div class="box"><table><thead><tr><th>코인</th><th>매수가</th><th>현재가</th><th>수익률</th><th>현재점수</th><th>진입 ATR</th></tr></thead><tbody>${posRows}</tbody></table></div></section><section class="panel"><h2>10분별 매매 판단 일지</h2><div class="box">${journals}</div></section><section class="panel"><h2>가상 체결 기록</h2><div class="box"><table><thead><tr><th>시각</th><th>구분</th><th>코인</th><th>체결가</th><th>수수료</th><th>실현손익</th><th>이유</th></tr></thead><tbody>${tradeRows}</tbody></table></div></section><section class="panel"><h2>공개된 매매 규칙</h2><p><b>매수:</b> 6/7점 이상, RSI≤68, 거래량≥평균 1.2배, 거래대금 10억원 이상. 종목당 200만원, 최대 5종목.</p><p><b>재진입 제한:</b> 매도된 코인은 최소 1시간 동안 다시 사지 않습니다.</p><p><b>안전:</b> PAPER 모드만 사용하며 실제 거래소 주문은 0건입니다.</p></section>`;
    const heldPanel=[...main.querySelectorAll('.panel')].find(panel=>panel.querySelector('h2')?.textContent.includes('현재 가상 보유')),heldHeader=heldPanel?.querySelector('thead tr');if(heldHeader){const targetHead=document.createElement('th');targetHead.textContent='목표가';heldHeader.insertBefore(targetHead,heldHeader.children[2])}
    const tradePanel=[...main.querySelectorAll('.panel')].find(panel=>panel.querySelector('h2')?.textContent.includes('가상 체결 기록'));if(tradePanel)tradePanel.querySelector('thead tr').innerHTML='<th>시각</th><th>구분</th><th>코인</th><th>매수가</th><th>매도가</th><th>수익률</th><th>실현손익</th><th>수수료</th><th>이유</th>';
    const rules=main.querySelector('.panel:last-child');if(rules)rules.querySelector('h2').insertAdjacentHTML('afterend','<p><b>목표가:</b> 매수가 대비 +6%입니다. 보유 표에서 종목별 계산 가격을 바로 확인할 수 있습니다.</p>');
    const canvas=document.getElementById('chart'),curve=state.curve||[];if(canvas&&curve.length){const x=canvas.getContext('2d'),values=curve.map(z=>Number(z.value)),min=Math.min(...values)*.999,max=Math.max(...values)*1.001,span=max-min||1;x.strokeStyle='#20344b';for(let y=30;y<190;y+=40){x.beginPath();x.moveTo(35,y);x.lineTo(1180,y);x.stroke()}x.strokeStyle='#2ad4a7';x.lineWidth=4;x.beginPath();curve.forEach((z,i)=>{const px=35+i*1140/Math.max(curve.length-1,1),py=185-(Number(z.value)-min)/span*150;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
  }
  const style=document.createElement('style');style.textContent='.live-status{border-radius:12px;padding:12px 14px}.live-status.ok{background:#0b2d28;border:1px solid #1b806b;color:#bdf7e8}.live-status.warn{background:#3a2b0b;border:1px solid #b17b16;color:#ffe4a3}.target-rate{color:#2ad4a7;font-weight:800;white-space:nowrap}.performance-cards{grid-template-columns:repeat(6,minmax(0,1fr))}.card small{display:block;color:#8fa3ba;margin-top:6px;line-height:1.35}.expectancy-card{border-color:#2a6b60;background:linear-gradient(145deg,#0a1727,#0b2b2a)}.expectancy-help{border-color:#285f57}@media(max-width:1100px){.performance-cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.performance-cards{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(style);
  load().catch(error=>{const main=document.querySelector('main.wrap');if(main)main.insertAdjacentHTML('afterbegin',`<p class="live-status warn"><b>데이터 표시 오류</b> · ${esc(error.message)}</p>`)});
})();

